language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
sudo: false
env:
 global:
   - PACKAGE="cohttp"
   - DEPOPTS="async_ssl ssl lwt js_of_ocaml"
   - POST_INSTALL_HOOK="opam depext -ui github cowabloga opium slacko"
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.02.3
   - DISTRO=debian-testing OCAML_VERSION=4.02.3
   - DISTRO=debian-unstable OCAML_VERSION=4.02.3
   - DISTRO=ubuntu-12.04 OCAML_VERSION=4.02.3
   - DISTRO=ubuntu-16.04 OCAML_VERSION=4.03.0
   - DISTRO=centos-6 OCAML_VERSION=4.02.3
   - DISTRO=centos-7 OCAML_VERSION=4.03.0
   - DISTRO=fedora-23 OCAML_VERSION=4.02.3
   - DISTRO=alpine OCAML_VERSION=4.02.3
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6ee5059c7420709f4ad1
    on_success: change
    on_failure: always
    on_start: false
